import ReactMarkdown from 'react-markdown';
import { SimpleLayout } from '@/layouts/simple';

export default function TermsOfServiceView() {
  return (
    <SimpleLayout
      slotProps={{
        content: { compact: true },
      }}
    >
      <ReactMarkdown>{MESSAGE}</ReactMarkdown>
    </SimpleLayout>
  );
}

const MESSAGE = `# Terms of Service

NORMAL PROTOCOL TERMS OF USE

Version 1.0

Last revised on: March 26, 2025

These Terms of Service (“Terms”) govern your use of the Normal Protocol (“Normal”) and related services offered by Normal Finance, Inc. (“Normal”) and its affiliates (together, “the Company,” “us,” “our,” and “we”) through this website (“Site”).

CRYPTOASSETS POSE UNIQUE RISKS. SEE SECTION 7 FOR A DETAILED EXPLANATION OF THESE RISKS. IF YOU DO NOT ACCEPT THESE RISKS, PLEASE CEASE USING THE SITE.

Your submission of information, including personal information, through or in connection with the Site is governed by the terms of our privacy policy as updated from time to time (“Privacy Policy”). All such additional terms, guidelines, and rules, including our Privacy Policy, are incorporated by reference into these Terms.

***

THESE TERMS SET FORTH THE LEGALLY BINDING TERMS AND CONDITIONS THAT GOVERN YOUR USE OF THE SITE. BY ACCESSING OR USING THE SITE, YOU ARE ACCEPTING THESE TERMS (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT), AND YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ENTER INTO THESE TERMS (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT). IF YOU DO NOT AGREE WITH ALL OF THE PROVISIONS OF THESE TERMS, DO NOT ACCESS AND/OR USE THE SITE.

THESE TERMS REQUIRE THE USE OF ARBITRATION (SECTION 18.2) ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES, RATHER THAN JURY TRIALS OR CLASS ACTIONS, AND ALSO LIMIT THE REMEDIES AVAILABLE TO YOU IN THE EVENT OF A DISPUTE.

WE RESERVE THE RIGHT TO AMEND THESE TERMS AT ANY TIME AND WILL NOTIFY YOU OF ANY SUCH CHANGES BY POSTING THE REVISED TERMS ON OUR WEBSITE, NORMALFINANCE.IO AND/OR APP.NORMALFINANCE.IO. YOU SHOULD CHECK THE TERMS ON OUR WEBSITE PERIODICALLY FOR CHANGES. ALL CHANGES SHALL BE EFFECTIVE UPON POSTING. WE WILL DATE THE TERMS WITH THE LAST DAY OF REVISION. YOUR CONTINUED USE OF THE SITE AFTER ANY CHANGE TO THESE TERMS CONSTITUTES YOUR AGREEMENT TO BE BOUND BY ANY SUCH CHANGES.

***

1. DESCRIPTION OF THE SERVICES\
   1.1. The Site provides qualified persons (“Users”) with an interface through which they can receive information about, and perform various actions relating to, certain digital assets that are “synthetic” using the Normal protocol (“Normal Tokens”). A “synthetic” asset is a digital asset that has been deployed to a non-native blockchain, with a different asset (typically its corresponding canonical asset) serving as collateral for that synthetic asset. Among other things, the Site provides Users with an interface to buy and sell Normal Tokens. Users can access the Site to receive information about Normal Tokens, communicate with Merchants about buying or selling Normal Tokens, and connect to third-party platforms to effectuate transactions or other actions in Normal Tokens. Only merchants are permitted to create and redeem Normal Tokens through the smart contracts. In acquiring a Normal Token, you do not acquire any claim to the underlying asset or possess any right to redeem the Normal Token for the underlying asset.\
   While certain Normal Tokens may be created or redeemed by using the Services, the Company does not endorse any particular Normal Token or otherwise offer any advice or recommendations with respect to a particular Normal Token. Any Normal Token that is made available through the Site is not intended to be, and should be construed as, personalized financial advice to you.\
   1.2. To use some of the Services on the Site, you must have access to a compatible virtual currency wallet (“Wallet”). Any Normal Tokens you acquire through the Site will be held and administered solely by you through your Wallet, and we shall have no access to or responsibility in regard to your Wallet or any Normal Token held in your Wallet. It is solely your responsibility to determine what Wallet software to use in connection with the Site, and your use of such Wallets are subject to any governing terms of use or privacy policy of such Wallet. While the Company has added support for certain Wallets and Normal Tokens on the site, you acknowledge and agree that we are under no obligation to continue to support those Wallets or those Normal Tokens, or to add additional support for other Wallets or other Normal Tokens, and that the inclusion of any particular Wallet or Normal Token is not an endorsement by us of such Wallet or Normal Token.\
   1.3. We will not create a hosted Wallet for you or otherwise custody Normal Tokens on your behalf, and it is your sole responsibility to maintain the security of your Wallet. In the event that you lose access to your Wallet, a private key, password, or other method of securing your Wallet, the assets in that Wallet may be irretrievable, and we will be unable to assist you in any way. You hereby irrevocably waive, release and discharge all claims, whether known or unknown to you, against the Company, its affiliates and their respective shareholders, members, directors, officers, employees, agents and representatives related to your use of any Wallet software, associated loss of assets, transaction failures, or any other defects that arise in the course of your use of your Wallet.\
   1.4. We reserve the right to modify, suspend or discontinue, temporarily or permanently, all or any part of our Site with or without notice. You agree that we will not be liable to you or to any third party for any modification, suspension or discontinuance of all or any part of our Site.\
   1.5. THE SITE IS AN ADMINISTRATIVE PLATFORM ONLY. WE ARE NOT A BROKER, DEALER, FINANCIAL INSTITUTION, EXCHANGE, CUSTODIAN, ROBO-ADVISOR, INTERMEDIARY, MONEY TRANSMITTER, OR CREDITOR. THE SITE DOES NOT EFFECTUATE TRANSACTIONS BETWEEN BUYERS AND SELLERS, WHICH TRANSACTIONS OCCUR ON THIRD-PARTY, UNAFFILIATED PLATFORMS. THE COMPANY IS NOT A COUNTERPARTY TO ANY TRANSACTION ON THE SITE OR FOR ANY USER OF THE SITE. NEITHER THE SITE NOR THE COMPANY PROVIDES FINANCIAL ADVISORY, LEGAL, REGULATORY, OR TAX SERVICES DIRECTLY, INDIRECTLY, IMPLICITLY, OR IN ANY OTHER MANNER, AND YOU SHOULD NOT CONSIDER ANY CONTENT CONTAINED IN THIS AGREEMENT OR OTHERWISE POSTED ON THE SITE TO BE A SUBSTITUTE FOR PROFESSIONAL FINANCIAL, LEGAL, REGULATORY, TAX OR OTHER ADVICE. THE COMPANY DOES NOT SUPPORT OR ENDORSE ANY UNAFFILIATED PROVIDER OR RECIPIENT OF THE SERVICES, AND EACH UNAFFILIATED PROVIDER AND RECIPIENT OF THE SERVICES IS AN INDEPENDENT AGENT WITH NO EMPLOYMENT RELATIONSHIP WITH THE COMPANY.
2. USE OF SITE\
   2.1. Normal Tokens cannot be purchased on the Site. Normal Tokens may be available for purchase via third-party platforms that may be accessed through this Site. The cost to purchase Normal Tokens on a third-party platform will be determined by that platform and/or counterparty to the transaction, and there may be costs or fees associated with that purchase. The Company is not liable for any such costs or fees that are incurred when buying Normal Tokens on a third-party platform, or for any operational disruptions or failures on a third-party platform that occur when purchasing Normal Tokens.\
   2.2. Normal Tokens cannot be sold on the Site. Normal Tokens may be available to be sold via third-party platforms that may be accessed through this Site. The price to sell Normal Tokens on a third-party platform, and the denomination in which the sale proceeds will be paid, will be determined by that platform at the time of sale and/or by the counterparty to the transaction. There may be costs or fees associated with a sale of the Normal Tokens. The Company is not liable for any such costs or fees that are incurred when selling Normal Tokens on a third-party platform, or for any operational disruptions or failures on a third-party platform when selling Normal Tokens.
3. USER VERIFICATION\
   3.1. Required Information. In order to use certain features of the Site, you must first log in with your Wallet and you may be required to provide certain personally identifiable information to verify your identity and your eligibility to access the Services. The Company is not liable if you mishandle, disclose or otherwise share your personal information with third parties outside of the Services.\
   3.2. Consent to access, processing and storage of your personally identifiable information or personal data (“Personal Data”). You consent to the Company and its assigns and designated vendors accessing, processing and retaining any personal information that you provide to us for the purpose of providing Services to you. This consent is not related to, and does not affect, any rights or obligations we or you have in accordance with data protection laws, privacy laws, and regulations. Please see our Privacy Policy for further information about how we process your Personal Data, and your corresponding rights.
4. FEES\
   4.1. Some of the Services involve the use of a blockchain network, which may require that you pay a fee, commonly known as a “Gas Fee,” for the computational resources required to perform a transaction. These fees may be reflected in the information you access through the Site. You acknowledge and agree that the Company has no control over: (a) the cost or the time to process a blockchain transaction; (b) the method of payment of any Gas Fee; or (c) any actual payments of Gas Fees.\
   We may assess fees and/or commissions to use the Site and the Services, and we reserve the right to levy additional fees in the future or change any existing fees, including fees for access to information or service fees to support the operation of the Site. You agree to promptly pay such fees and commissions, as set forth on the Site and as applicable to the Services you receive, which we may modify from time to time. In the event that we add fees to the Site or any of our Services, we will post a notification on the Site prior to any such fees going into effect.\
   Notwithstanding anything in these Terms to the contrary, it is your sole responsibility to determine whether, and to what extent, any taxes apply to your usage of the Site, and to withhold, collect, report and remit the correct amount of taxes to the appropriate tax authorities.
5. ELIGIBILITY\
   5.1. As a condition of accessing the Site, you represent and warrant to the Company the following:\
   (A) If you are entering into these Terms as an individual, then you are at least 18 years old or of legal age to enter into contractual relations with the Company (whichever is later).\
   (B) If you are entering into these Terms as an entity, then you must have the legal authority to accept these Terms on that entity’s behalf, in which case “you” (except as used in this paragraph) will mean that entity.\
   (c) You will provide all requested information, and all such information is correct, current and complete.\
   (D) You have not been identified as a Specially Designated National or placed on any sanctions list by the U.S. Treasury Department’s Office of Foreign Assets Control, the U.S. Commerce Department, or the U.S. Department of State; and you will not use our Site to conduct any illegal or illicit activity.\
   (e) You have not been placed on any of the following lists: European External Action Service Consolidated Financial Sanctions List; EU Terrorist List; FATF Non-Cooperative Countries and Territories; Federal Bureau of Investigation Most Wanted Terrorists & Seeking Information; Bank of England Sanctions List; HM Treasury Sanctions List; Politically Exposed Persons List; World Bank Ineligible Firms; Department of Foreign Affairs and Trade Consolidated List.\
   (f) You are not a resident, national, or agent of Antigua and Barbuda, Algeria, Bangladesh, Bolivia, Belarus, Burundi, Burma (Myanmar), Cote D’Ivoire (Ivory Coast), Crimea and Sevastopol, Cuba, Democratic Republic of Congo, Ecuador, Iran, Iraq, Liberia, Libya, Magnitsky, Mali, Morocco, Nepal, North Korea, Somalia, Sudan, Syria, Venezuela, Yemen, Zimbabwe or any other country to which the United States, the United Kingdom or the European Union embargoes goods or imposes similar sanctions (collectively, “Restricted Territories”);\
   (G) You do not, and will not, use VPN software or any other privacy or anonymization tools or techniques to circumvent, or attempt to circumvent, any restrictions that apply to the Site.\
   (h) You represent that your access and use of the Site will fully comply with all applicable laws and regulations, and that you will not access or use the Site to conduct, promote, or otherwise facilitate any illegal activity.\
   (i) You will use your own judgment, conduct your own due diligence and seek any legal, financial, tax, accounting and other professional advice that may be appropriate before making any decision to transact in a Normal Tokent.\
   (j) You agree and acknowledge that the Company retains sole discretion to terminate your access to Services for any reason or no reason at all.
6. NO INVESTMENT ADVICE OR FIDUCIARY DUTIES\
   6.1. The Company is not engaged in the business of the offer, sale or trading of securities or other financial instruments and does not provide legal, tax, or investment advice. All information provided in connection with your access and use of the Site is for informational purposes only and should not be construed as professional or investment advice. You should not take, or refrain from taking, any action based on any information contained on the Site or any other information that we make available at any time, including, without limitation, blog posts, articles, links to third-party content, Discord content, news feeds, tutorials, tweets, and videos. Before you make any financial, legal, or other decisions involving the Site, you should seek independent professional advice from an individual who is licensed and qualified in the area for which such advice would be appropriate. These Terms are not intended to, and do not, create or impose any fiduciary duties on us. You further agree that the only duties and obligations that we owe you are those set out expressly in these Terms.\
   6.2. You understand and acknowledge that you are solely responsible for any and all actions that you undertake using the Services and the Site, and all instructions entered by you are unsolicited and based on your own decisions. You understand and acknowledge that you have not received and do not expect to receive any advice from the Company in connection with your use of the Services. Notwithstanding anything in these Terms, you understand and acknowledge that the Company accepts no responsibility whatsoever for, and shall in no circumstances be liable to you in connection with, your decisions or any gains/losses created through User decisions. You further understand and acknowledge that under no circumstances will your use of the Services be deemed to create a relationship that includes the provision or tendering of investment advice. You acknowledge that neither the Company nor its employees, agents, principals or representatives, nor any of our affiliates or their employees, agents, principals, or representatives (i) provide investment advice in connection with the Site or the Services, (ii) recommend any Normal Tokens or related transactions, or (iii) solicit Services. To the extent research materials or similar information are made available through the Site, you hereby understand and acknowledge that these materials are intended for informational and educational purposes only and do not constitute a recommendation by the Company to enter into any transactions or to engage in any investment strategies.
7. ACKNOWLEDGEMENT OF RISKS\
   7.1. By accessing or using the Site in any way, you represent and warrant that you understand the inherent risks associated with cryptographic systems and blockchain-based networks; digital assets in general and Normal Tokens in particular, including the usage and intricacies of smart contract-based tokens, such as those that follow the Ethereum Token Standard; and systems that interact with blockchain-based networks. Apart from the Normal Protocol, the Company does not own or control any of the underlying software through which blockchain networks are formed. In general, the software underlying blockchain networks is open-source, such that anyone can use, copy, modify, and distribute it.\
   7.2. By accessing or using the Site, you acknowledge and agree that (a) the Company is not responsible for the operation of the software and networks underlying the Site, (b) there exists no guarantee of the functionality, security, or availability of that software and networks, and (c) the underlying networks are subject to sudden changes in operating rules, such as those commonly referred to as “forks,” which may materially affect the Site.\
   7.3. IN ACCESSING THE SITE AND USING ANY SERVICES, YOU ACKNOWLEDGE THAT WE MAY, AT ANY TIME AND FOR ANY REASON, LIQUIDATE SOME OR ALL OF THE UNDERLYING ASSETS THAT FORM THE BASIS OF A “SYNTHETIC” ASSET. AS PART OF THIS LIQUIDATION, WE MAY EITHER SUBSTITUTE THE UNDERLYING ASSET FOR OTHER ASSETS, SUCH AS USDC OR XLM, OR DEPRECATE THE Normal Token AND REDEEM HOLDERS OF THAT Normal Token WITH THE PROCEEDS OF THE LIQUIDATION.\
   7.4. Blockchain networks use public/private key cryptography. You acknowledge and understand that you alone are responsible for securing your private key(s). We do not have access to your private key(s). Losing control of your private key(s) will permanently and irreversibly deny you access to Normal Tokens and other digital assets in your Wallet. Neither the Company nor any other person or entity will be able to retrieve or protect your Normal Tokens. If your private key(s) are lost, then you will not be able to transfer your Normal Tokens to any other blockchain address or wallet or sell those Normal Tokens. If this occurs, then you will not be able to realize any value or utility from the Normal Tokens that you may hold in your Wallet.\
   7.6. The regulatory status of digital assets is uncertain in many jurisdictions. You acknowledge and understand that the Site and your Normal Tokens could be impacted by regulatory inquiries or regulatory actions, which could impede or limit the ability of the Company to continue to make available any portion(s) of the Site or the Services and which could impede or limit your ability to access or use the Site or the Services.\
   7.7. You acknowledge and understand that cryptography is a developing field with advances in cyber intrusion and other technical advancements, such as the development of quantum computers, which may present risks to Normal Tokens and the Site, and which could result in theft or loss of your Normal Tokens, or difficulty in using the Site and the Services. The Company may limit access to the Site and the Services in the event of a critical security problem, but this does not guarantee or otherwise ensure full security of the Site.\
   7.8. You understand that blockchain technology remains under development, which creates technological and security risks when using the Site. You acknowledge that the cost of transacting on a blockchain is variable and may increase at any time, which may be reflected in the information you receive through the Site.\
   7.9. You acknowledge that the Site and the Services may be subject to flaws and that you are solely responsible for evaluating any code provided by the Site. This statement and others set forth in these Terms in no way evidence or represent an on-going duty by the Company or its affiliates to alert you to all of the potential risks of using or accessing the Site and the Services.\
   7.10. Although we intend to provide accurate and timely information on the Site, the Site and other information available when using the Site may not always be entirely accurate, complete, or current and may also include technical inaccuracies or typographical errors. To continue to provide you with as complete and accurate information as possible, information may be changed or updated from time to time without notice, including, without limitation, information regarding our policies. Accordingly, you should verify all information before relying on it, and all decisions based on information contained on the Site are your sole responsibility. No representation is made as to the accuracy, completeness, or appropriateness for any particular purpose of any information distributed via the Site. Information such as prices and pricing information may be higher or lower than prices available on platforms providing similar services.\
   7.11. Any use or interaction with the Site requires a comprehensive understanding of applied cryptography and computer science to appreciate the inherent risks, including those listed above. You represent and warrant that you possess relevant knowledge and skills to properly utilize the Services. Any reference to a Normal Token on the Site does not indicate our approval or disapproval of the technology on which the Normal Token relies, and should not be used as a substitute for your understanding of the risks specific to each type of Normal Token.\
   7.12. Based on information received through the Site, you may enter into blockchain-based transactions on third-party platforms. Such transactions are irreversible, final and there are no refunds. You acknowledge and agree that you will access and use the Site and any related information at your own risk. The risk of loss in transacting in digital assets, including Normal Tokens, can be substantial. You should, therefore, carefully consider whether such activity is suitable for you in light of your circumstances and financial resources. By using or accessing the Site, you represent and warrant that you have been, are, and will be solely responsible for making your independent appraisal and investigations into the risks of a given transaction and the underlying Normal Tokens. You represent that you have sufficient knowledge, market sophistication, professional advice, and experience to make your evaluation of the merits and risks of any transaction conducted in connection with the Site or any Normal Token. You accept all consequences of using the Site, and represent that all decisions involving your use of the Services are made solely by you. Notwithstanding anything in these Terms, we accept no responsibility whatsoever for, and will in no circumstances be liable to you in connection with your use of the Site.\
   7.13. We must comply with Applicable Law, which may require us to, upon request by government agencies, take certain actions or provide information, including personally identifiable information or information related to your usage of the Services.\
   7.14. You understand that our Site remains under development, which creates technological, operational, and other risks when using or accessing the Site. These risks include, among others, an incorrect display of information on the Site in the case of server or code errors. You acknowledge that these risks may have a material impact on your usage of the Services, which may result in, among other things, a failure to fulfill the requested Services.\
   7.15. You hereby acknowledge and agree that the Company will have no responsibility or liability for the risks set forth in this Section 7. You hereby irrevocably waive, release and discharge all claims, whether known or unknown to you, against Normal, its affiliates, and their respective shareholders, members, directors, officers, employees, agents, and representatives, suppliers, and contractors related to any of the risks set forth in this Section 7.\
   7.16. Digital assets currently face an uncertain regulatory landscape in the United States and many foreign jurisdictions. One or more jurisdictions may, in the future, adopt laws, regulations or directives that affect digital asset networks and their users. Such laws, regulations or directives may impact the price of digital assets and their acceptance by users, merchants and service providers. The Company has no control over these regulatory changes or the impact they may have on Users.
8. ACCESS TO THE SITE\
   8.1. License. Subject to these Terms, the Company grants you a non-transferable, non-exclusive, revocable, limited license to use and access the Site for your own personal and noncommercial use. This license is not for commercial use.\
   8.2. Certain Restrictions. The rights granted to you in these Terms are subject to the following restrictions: (i) you shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Site, whether in whole or in part, or any content displayed on the Site; (ii) you shall not (directly or indirectly) modify, decipher, disassemble, reverse compile or reverse engineer or otherwise attempt to derive any source code or underlying ideas or algorithms of any part of the Services or the Site; (iii) you shall not access the Site in order to build a similar or competitive website, product, or service; (iv) translate, or otherwise create derivative works of any part of the Services or Site; (v) rent, lease, distribute, or otherwise transfer any of the rights that you receive hereunder; (vi) frame or mirror any part of the Site without the Company’s express prior written consent; (vii) create a database by systematically downloading and storing Site content; (viii) use any robot, spider, site search/retrieval application or other manual or automatic device to retrieve, harvest, index, “scrape,” “data mine” or in any way gather Site content or reproduce or circumvent the navigational structure or presentation of the Site without the Company’s express prior written consent and (ix) except as expressly stated herein, no part of the Site may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means. Unless otherwise indicated, any future release, update, or other addition to functionality of the Site shall be subject to these Terms. All copyright and other proprietary notices on the Site (or on any content displayed on the Site) must be retained on all copies thereof.\
   8.3. Availability of the Site and Services. The Site and some or all of the Services may not be appropriate or available for use in some jurisdictions. The Company and its affiliates do not represent or warrant that the Site, the Services or any part thereof is appropriate or available for use in any particular jurisdiction. In choosing to access the Site, you do so on your own initiative and at your own risk, and you are responsible for complying with all local laws, rules and regulations.\
   8.4. Modification of the Site. The Company reserves the right, at any time, to modify, suspend, or discontinue the Site (in whole or in part) with or without notice to you. You agree that the Company will not be liable to you or to any third party for any modification, suspension, or discontinuation of the Site or any part thereof.\
   8.5. You acknowledge and agree that the Company has no obligation to provide you with any support or maintenance in connection with the Site, unless specifically contracted for under a separate agreement.\
   8.6. Ownership. Excluding any User Content that you may provide (defined below), you acknowledge that all the intellectual property rights, including copyrights, patents, trademarks, and trade secrets in the Site and its content are owned by the Company. Neither these Terms (nor your access to the Site) transfers to you or any third party any rights, title or interest in or to such intellectual property rights, except for the limited access rights expressly set forth in these Terms. The Company reserves all rights not granted in these Terms. There are no implied licenses granted under these Terms.
9. USER CONTENT\
   9.1. User Content. “User Content” means any and all information and content that a User submits to, or uses with, the Site (e.g., profile picture). You are solely responsible for your User Content. You assume all risks associated with use of your User Content, including any reliance on its accuracy, completeness or usefulness by others, or any disclosure of your User Content that personally identifies you or any third party. You hereby represent and warrant that your User Content does not violate our Acceptable Use Policy (defined in Section 9.2). You may not represent or imply to others that your User Content is in any way provided, sponsored or endorsed by the Company. Because you alone are responsible for your User Content, you may expose yourself to liability if, for example, your User Content violates the Acceptable Use Policy. The Company is not obligated to back up any User Content, and your User Content may be deleted at any time without prior notice. You are solely responsible for creating and maintaining your own backup copies of your User Content if you desire.\
   9.2. Acceptable Use Policy. The following terms constitute our “Acceptable Use Policy”:\
   You agree not to use the Site to collect, upload, transmit, display, or distribute any User Content (i) that violates any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (ii) that is unlawful, harassing, abusive, tortious, threatening, harmful, invasive of another’s privacy, vulgar, defamatory, false, intentionally misleading, trade libelous, pornographic, obscene, patently offensive, promotes racism, bigotry, hatred, or physical harm of any kind against any group or individual or is otherwise objectionable; (iii) that is harmful to minors in any way; or (iv) that is in violation of any law, regulation, or obligations or restrictions imposed by any third party.\
   In addition, you agree not to: (i) upload, transmit, or distribute to or through the Site any computer viruses, worms, or any software intended to damage or alter a computer system or data; (ii) send through the Site unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of duplicative or unsolicited messages, whether commercial or otherwise; (iii) use the Site to harvest, collect, gather or assemble information or data regarding other users, including e-mail addresses, without their consent; (iv) interfere with, disrupt, or create an undue burden on servers or networks connected to the Site, or violate the regulations, policies or procedures of such networks; (v) attempt to gain unauthorized access to the Site (or to other computer systems or networks connected to or used together with the Site), whether through password mining or any other means; (vi) harass or interfere with any other user’s use and enjoyment of the Site; or (vii) use software or automated agents or scripts to produce multiple accounts on the Site, or to generate automated searches, requests, or queries to (or to strip, scrape, or mine data from) the Site (provided, however, that we may conditionally grant to the operators of public search engines revocable permission to use spiders to copy materials from the Site for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials, subject to the parameters set forth in our robots.txt file).\
   9.3. Enforcement. We reserve the right (but have no obligation) to review any User Content, and to investigate and/or take appropriate action against you in our sole discretion if you violate the Acceptable Use Policy or any other provision of these Terms or otherwise create liability for us or any other person. Such action may include restricting your access to the Site and/or reporting you to law enforcement authorities.\
   9.4. Feedback. If you provide the Company with any feedback or suggestions regarding the Site (“Feedback”), you hereby assign to the Company all rights in such Feedback and agree that the Company shall have the right to use and fully exploit such Feedback and related information in any manner it deems appropriate. The Company will treat any Feedback you provide to us as non-confidential and non-proprietary. You agree that you will not submit to the Company any information or ideas that you consider to be confidential or proprietary.
10. INDEMNIFICATION\
    You agree to indemnify and hold the Company and its affiliates (and their respective directors, officers, employees, and agents) harmless, including costs and attorneys’ fees, from any claim or demand made by any third party due to or arising out of (i) your use of the Site, the Services or a Normal Token; (ii) your violation of these Terms; (iii) your violation of applicable laws or regulations; or (iv) your User Content. The Company reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of the Company. We will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.
11. THIRD-PARTY LINKS & ADS\
    You hereby release and forever discharge the Company and its affiliates (and their respective directors, officers, employees, agents, successors, and assigns) from, and hereby waive and relinquish, each and every past, present and future dispute, claim, controversy, demand, right, obligation, liability, action and cause of action of every kind and nature (including personal injuries, death, and property damage), that has arisen or arises directly or indirectly out of, or that relates directly or indirectly to, the Site (including any interactions with, or act or omission of, other Site users or any Third-Party Links & Ads). IF YOU ARE A CALIFORNIA RESIDENT, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE SECTION 1542 IN CONNECTION WITH THE FOREGOING, WHICH STATES: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FA VOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER WOULD HA VE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.”
12. ACCURACY OF INFORMATION\
    We attempt to ensure that the information that we provide on this Site is complete, accurate and current. Despite our efforts, the information on this Site may occasionally be inaccurate, incomplete or out of date. We make no representation as to the completeness, accuracy or correctness of any information on this Site.
13. DISCLAIMERS\
    THE SITE IS PROVIDED ON AN “AS-IS” AND “AS A V AILABLE” BASIS, AND THE COMPANY (AND OUR VENDORS) EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY , INCLUDING ALL WARRANTIES OR CONDITIONS OF MERCHANTABILITY , FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY , OR NON-INFRINGEMENT. WE (AND OUR VENDORS) MAKE NO WARRANTY THAT THE SITE WILL MEET YOUR REQUIREMENTS, WILL BE A V AILABLE ON AN UNINTERRUPTED, TIMELY , SECURE, OR ERROR-FREE BASIS, WILL BE ACCURATE, RELIABLE, FREE OF VIRUSES OR OTHER HARMFUL CODE, AND WILL BE COMPLETE, LEGAL, OR SAFE. IF APPLICABLE LAW REQUIRES ANY WARRANTIES WITH RESPECT TO THE SITE, ALL SUCH WARRANTIES ARE LIMITED IN DURATION TO NINETY (90) DAYS FROM THE DATE OF FIRST USE.\
    YOU ACKNOWLEDGE THAT YOU ARE NOT RELYING ON THE COMPANY IN MAKING ANY DECISIONS TO USE THE SITE OR THE SERVICES. THE COMPANY DOES NOT ENDORSE ANY THIRD PARTY AND SHALL NOT BE RESPONSIBLE IN ANY WAY FOR ANY TRANSACTIONS YOU ENTER INTO WITH OTHER USERS OR THROUGH YOUR USE OF THE SITE. YOU AGREE THAT THE COMPANY WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGES OF ANY SORT INCURRED AS THE RESULT OF ANY INTERACTIONS THAT OCCUR THROUGH YOUR USE OF THE SITE.\
    SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU. SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.
14. LIMITATION ON LIABILITY\
    TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL THE COMPANY BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFITS, LOST DATA, OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY , INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM OR RELATING TO THESE TERMS OR YOUR USE OF, OR INABILITY TO USE, THE SITE, EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ACCESS TO, AND USE OF, THE SITE IS AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR DEVICE OR COMPUTER SYSTEM, OR LOSS OF DATA RESULTING THEREFROM.\
    THE COMPANY SHALL NOT BE LIABLE FOR ANY LOSS OR DAMAGE AS A RESULT OF YOUR FAILURE TO KEEP YOUR ACCESS TO THE SITE SECURE. THE COMPANY SHALL NOT LIABLE FOR ANY LOSS OR DAMAGE ARISING FROM YOUR FAILURE TO MAINTAIN THE CONFIDENTIALITY OF YOUR FINANCIAL INFORMATION.\
    TO THE MAXIMUM EXTENT PERMITTED BY LAW, NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY DAMAGES ARISING FROM OR RELATED TO THIS AGREEMENT (FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION), WILL AT ALL TIMES NOT EXCEED THE GREATER OF FIVE HUNDRED US DOLLARS (U.S. $500) OR THE AMOUNT OF ANY FEES YOU HA VE PAID TO USE THE SITE AND THE SERVICES IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING YOUR CLAIM. THE EXISTENCE OF MORE THAN ONE CLAIM WILL NOT ENLARGE THIS LIMIT.\
    SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.
15. TERM AND TERMINATION\
    Subject to this Section, these Terms will remain in full force and effect while you use the Site. We may suspend or terminate your rights to use the Site at any time for any reason at our sole discretion, including for any use of the Site in violation of these Terms. Upon termination of your rights under these Terms, your right to access and use the Site will terminate immediately. You understand that any termination of your rights may involve the removal of your User Content associated with your Wallet from our live databases. The Company will not have any liability whatsoever to you for any termination of your rights under these Terms, including for terminating your access to the Site and the Services. Even after your rights under these Terms are terminated, the following provisions of these Terms will remain in effect: Sections 3.2 through 6, and Sections 4 through 8 and Sections 10 through 11.
16. DISPUTE RESOLUTION\
    Please read this Arbitration Agreement carefully. It is part of your contract with The Company and affects your rights. It contains procedures for MANDATORY BINDING ARBITRATION AND A CLASS ACTION WAIVER.\
    16.1 Applicability of Arbitration Agreement. All claims and disputes (excluding claims for injunctive or other equitable relief as set forth below) between the Company and any User or Registered User that cannot be resolved informally or in small claims court shall be resolved by binding arbitration on an individual basis under the terms of this Arbitration Agreement. Unless otherwise agreed to, all arbitration proceedings shall be held in English. This Arbitration Agreement applies to you and the Company, and to any subsidiaries, affiliates, agents, employees, predecessors in interest, successors, and assigns, as well as all authorized or unauthorized users or beneficiaries of services or goods provided under the Terms.\
    16.2 Notice Requirement and Informal Dispute Resolution. Before either party may seek arbitration, the party must first send to the other party a written Notice of Dispute (“Notice”) describing the nature and basis of the claim or dispute, and the requested relief. A Notice to the Company should be sent to the address set forth in Section 23. After the Notice is received, you and the Company may attempt to resolve the claim or dispute informally. If you and the Company do not resolve the claim or dispute within thirty (30) days after the Notice is received, either party may begin an arbitration proceeding. The amount of any settlement offer made by any party may not be disclosed to the arbitrator until after the arbitrator has determined the amount of the award, if any, to which either party is entitled.\
    16.3 Arbitration Rules. Arbitration shall be initiated through the American Arbitration Association (“AAA”), an established alternative dispute resolution provider (“ADR Provider”) that offers arbitration as set forth in this section. If AAA is not available to arbitrate, the parties shall agree to select an alternative ADR Provider. The rules of the ADR Provider shall govern all aspects of the arbitration, including but not limited to the method of initiating and/or demanding arbitration, except to the extent such rules are in conflict with the Terms. The AAA Consumer Arbitration Rules (“Arbitration Rules”) governing the arbitration are available online at [www.adr.org](http://www.adr.org/) or by calling the AAA at 1-800-778-7879. The arbitration shall be conducted by a single, neutral arbitrator. Any claims or disputes where the total amount of the award sought is less than Ten Thousand U.S. Dollars (US $10,000.00) may be resolved through binding non-appearance-based arbitration, at the option of the party seeking relief. For claims or disputes where the total amount of the award sought is Ten Thousand U.S. Dollars (US $10,000.00) or more, the right to a hearing will be determined by the Arbitration Rules. Any hearing will be held in a location within 100 miles of your residence, unless you reside outside of the United States, or unless the parties agree otherwise.\
    If you reside outside of the United States, the arbitrator shall give the parties reasonable notice of the date, time and place of any oral hearings. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. If the arbitrator grants you an award that is greater than the last settlement offer that the Company made to you prior to the initiation of arbitration, the Company will pay you the greater of the award or $2,500.00. Each party shall bear its own costs (including attorney’s fees) and disbursements arising out of the arbitration and shall pay an equal share of the fees and costs of the ADR Provider.\
    16.4. Additional Rules for Non-Appearance Based Arbitration. If non-appearance based arbitration is elected, the arbitration shall be conducted by telephone, online and/or based solely on written submissions; the specific manner shall be chosen by the party initiating the arbitration. The arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise agreed by the parties.\
    16.5 Time Limits. If you or the Company pursue arbitration, the arbitration action must be initiated and/or demanded within the statute of limitations (i.e., the legal deadline for filing a claim) and within any deadline imposed under the AAA Rules for the pertinent claim.\
    16.6 Authority of Arbitrator. If arbitration is initiated, the arbitrator will decide the rights and liabilities, if any, of you and the Company, and the dispute will not be consolidated with any other matters or joined with any other cases or parties. The arbitrator shall have the authority to grant motions dispositive of all or part of any claim. The arbitrator shall have the authority to award monetary damages, and to grant any non-monetary remedy or relief available to an individual under applicable law, the AAA Rules, and the Terms. The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded. The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The award of the arbitrator is final and binding upon you and Normal.\
    16.7 Waiver of Jury Trial. THE PARTIES HEREBY WAIVE THEIR CONSTITUTIONAL AND STATUTORY RIGHTS TO GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY, instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement. Arbitration procedures are typically more limited, more efficient and less costly than rules applicable in a court and are subject to very limited review by a court. In the event any litigation should arise between you and the Company in any court of competent jurisdiction in a suit to vacate or enforce an arbitration award or otherwise, YOU AND THE COMPANY WAIVE ALL RIGHTS TO A JURY TRIAL, instead electing that the dispute be resolved by a judge.\
    16.8 Waiver of Class or Consolidated Actions. ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR LITIGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER.\
    16.9 Confidentiality. All aspects of the arbitration proceeding, including but not limited to the award of the arbitrator and compliance therewith, shall be strictly confidential. The parties agree to maintain confidentiality unless otherwise required by law. This paragraph shall not prevent a party from submitting to a court of law any information necessary to enforce this Agreement, to enforce an arbitration award, or to seek injunctive or equitable relief.\
    16.10 Severability. If any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable by a court of competent jurisdiction, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Agreement shall continue in full force and effect.\
    16.11 Right to Waive. Any or all of the rights and limitations set forth in this Arbitration Agreement may be waived by the party against whom the claim is asserted. Such waiver shall not waive or affect any other portion of this Arbitration Agreement.\
    16.12 Survival of Agreement. This Arbitration Agreement will survive the termination of your relationship with the Company\
    16.13 Small Claims Court. Notwithstanding the foregoing, either you or the Company may bring an individual action in small claims court.\
    16.14 Emergency Equitable Relief. Notwithstanding the foregoing, either party may seek emergency equitable relief before a court of competent jurisdiction in order to maintain the status quo pending arbitration. A request for interim measures shall not be deemed a waiver of any other rights or obligations under this Arbitration Agreement.\
    16.15 Claims Not Subject to Arbitration. Notwithstanding the foregoing, claims of defamation, violation of the Computer Fraud and Abuse Act, and infringement or misappropriation of the other party’s patent, copyright, trademark or trade secrets shall not be subject to this Arbitration Agreement.
17. DISCLOSURES\
    The Company is located at the address in Section 23.
18. ELECTRONIC COMMUNICATIONS\
    The communications between you and the Company are through electronic means, whether you use the Site or send us emails, or whether the Company posts notices on the Site or communicates with you via email. For contractual purposes, you (i) consent to receive communications from the Company in an electronic form; and (ii) agree that all terms and conditions, agreements, notices, disclosures, and other communications that the Company provides to you electronically satisfy any legal requirement that such communications would satisfy if it were be in a hardcopy form. The foregoing does not affect your non-waivable rights.
19. ENTIRE TERMS\
    These Terms constitute the entire agreement between you and us regarding the use of the Site and the Services. The section titles in these Terms are for convenience only and have no legal or contractual effect. The word “including” means “including without limitation.” If any provision of these Terms is, for any reason, held to be invalid or unenforceable, the other provisions of these Terms will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law. You confirm that you are acting on your own behalf and not for the benefit of any other person. Your relationship to the Company is that of an independent contractor, and neither party is an agent or partner of the other. These Terms, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without the Company’s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void. The Company may freely assign these Terms. The terms and conditions set forth in these Terms shall be binding upon all assignees.
20. WAIVER\
    A waiver by the Company of any right or remedy under these Terms shall only be effective if it is in writing, executed by a duly authorized representative of the Company and shall apply only to the circumstances for which it is given. Our failure to exercise or enforce any right or remedy under these Terms shall not operate as a waiver of such right or remedy, nor shall it prevent any future exercise or enforcement of such right or remedy. No single or partial exercise of any right or remedy shall preclude or restrict the further exercise of any such right or remedy or other rights or remedies.
21. GOVERNING LAW AND JURISDICTION\
    These Terms and any dispute or claim arising out of or in connection with their subject matter or formation (including non-contractual disputes or claims) shall be governed by and construed in accordance with the law of the State of Delaware.\
    The Site and some or all of the Services may not be appropriate or available for use in some jurisdictions. The Company and its partners do not represent or warrant that the Site or any part thereof is appropriate or available for use in any particular jurisdiction. In choosing to access the Site, you do so on your own initiative and at your own risk, and you are responsible for complying with all local laws, rules and regulations.\
    SOME JURISDICTIONS HAVE CONSUMER PROTECTION AND OTHER LEGISLATION WHICH MAY APPLY TO THE SERVICES AND WHICH DO NOT ALLOW CERTAIN PROVISIONS SUCH AS LIMITATIONS OF LIABILITY AND EXCLUSION OF CERTAIN WARRANTIES, AMONG OTHERS. TO THE EXTENT THAT A LIMITATION, EXCLUSION, RESTRICTION OR OTHER PROVISION IN THESE TERMS IS SPECIFICALLY PROHIBITED BY APPLICABLE LAW, SUCH LIMITATION, EXCLUSION, RESTRICTION OR PROVISION MAY NOT APPLY TO YOU.
22. COPYRIGHT / TRADEMARK INFORMATION\
    Copyright © 2025 Normal Finance, Inc. All rights reserved. All trademarks, logos and service marks (“Marks”) displayed on the Site are our property or the property of other third parties. You are not permitted to use these Marks without our prior written consent or the consent of such third party that may own the Marks.
23. CONTACT INFORMATION\
    Address: 254 Chapman Rd, Ste 208 #7553\
    Newark, DE 19702\
    Email: <hello@normalfinance.io>`;
